### Question 1: use arange to create a 2-by-2 array containing the numbers 0–3. Use broadcasting to perform each of the following operations on the original array:


```
a) Cube every element of the array.
b) Add 7 to every element of the array.
c) Multiply every element of the array by 2.

```



In [ ]:
#import numpy
import numpy as np

#create a 1D array using 'arange' by default increment is 1
#so you don't need to include that here
num = np.arange(0, 4)

#reshape to 2D array
num = num.reshape(2, 2)

#see your array
print(num)

[[0 1]
 [2 3]]


In [ ]:
#Cube every element of the array.
num_cube = num ** 3

print(num_cube)

[[ 0  1]
 [ 8 27]]


In [ ]:
#Add 7 to every element of the array.
num_sum = num + 7

print(num_sum)

[[ 7  8]
 [ 9 10]]


In [ ]:
#Multiply every element of the array by 2.
num_by_2 = num * 2

print(num_by_2)

[[0 2]
 [4 6]]


### Question 2: Create a 3-by-3 array containing the even integers from 2 through 18. Create a second 3-by-3 array containing the integers from 9 down to 1, then multiply the first array by the second.

In [14]:
#create a even number from 2 to 18.
array1 = np.arange(2, 19, 2)

#since the even numbers in this range is just 9 numbers not 16
#you can reshape using 3 by 3
array1 = array1.reshape(3, 3)

#create an integer array 9 to 1
array2 = np.arange(9, 0, -1)

#reshape it to 3 by 3
array2 = array2.reshape(3, 3)


In [15]:
#multiply the two arrays
result = array1 * array2

print(result)

[[18 32 42]
 [48 50 48]
 [42 32 18]]


### Question 3: Create an array containing the values 1–15, reshape it into a 3-by-5 array, then use indexing and slicing techniques to perform each of the following operations:



```
a) Select row 2.
b) Select column 5.
c) Select rows 0 and 1.
d) Select columns 2–4.
e) Select the element that is in row 1 and column 4.
f) Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.

```



In [16]:
#Create an array containing the values 1–15
num_array = np.arange(1, 16)

#reshape into 3 by 5
num_array = num_array.reshape(3, 5)

print(num_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [17]:
# a) Select row 2.
print(num_array[2])

[11 12 13 14 15]


In [23]:
# b) Select column 5.
print(num_array[:, 4]) # see all row selected with ':' and use ',' as seperator to move to column

[ 5 10 15]


In [24]:
# c) Select rows 0 and 1.
print(num_array[0:2]) #select consecutive rows except the last row (2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [25]:
# d) Select columns 2–4.
print(num_array[:, 2:5])# see all row selected with ':' and use ',' as seperator to move to column before selecting consecutive columns

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [26]:
# e) Select the element that is in row 1 and column 4.
print(num_array[1,4])

10


In [27]:
# f) Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.
print(num_array[1:3, [0, 2, 4]]) #select consecutive rows then put the needed columns in list to select them since they're not sequential

[[ 6  8 10]
 [11 13 15]]


### Question 4: Perform the following tasks with pandas Series:



```
a) Create a Series from the list [7, 11, 13, 17].
b) Create a Series with five elements that are all 100.0.
c) Create a Series with 20 elements that are all random numbers in the range 0 to 100. Use method describe to produce the Series’ basic descriptive statistics.
```



In [29]:
import pandas as pd

# a) Create a Series from the list [7, 11, 13, 17].
pandas_series = pd.Series([7, 11, 13, 17])

print(pandas_series)

0     7
1    11
2    13
3    17
dtype: int64


In [30]:
# b) Create a Series with five elements that are all 100.0.
pandas_series = pd.Series([100.0] * 5)

print(pandas_series)

0    100.0
1    100.0
2    100.0
3    100.0
4    100.0
dtype: float64


In [34]:
# c) Create a Series with 20 elements that are all random numbers in the range 0 to 100.
#Use method describe to produce the Series’ basic descriptive statistics.

num = np.random.randint(0, 100, size = 20)

pandas_series = pd.Series(num)

print(pandas_series, end = ' ')

0     84
1     23
2     26
3     68
4     21
5     88
6     12
7     37
8      5
9     56
10    36
11    55
12    27
13     6
14    72
15    61
16    34
17    60
18    91
19    12
dtype: int64 

### Question 5: Perform the following tasks with pandas DataFrames:



```
a) Create a DataFrame named temperatures from a dictionary of three temperature readings each for 'Maxine', 'James' and 'Amanda'.
b) Recreate the DataFrame temperatures in Part (a) with custom indices using
the index keyword argument and a list containing 'Morning', 'Afternoon'
and 'Evening'.
c) Select from temperatures the column of temperature readings for 'Maxine'.
d) Select from temperatures the row of 'Morning' temperature readings.
e) Select from temperatures the rows for 'Morning' and 'Evening' temperature
readings.

f) Use the describe method to produce temperatures’ descriptive statistics.


```



In [56]:
# a) Create a DataFrame named temperatures from a dictionary of three temperature readings each for 'Maxine', 'James' and 'Amanda'.
named_dict = {'Maxine': 30, 'James': 45, 'Amanda': -10}

temperature = pd.DataFrame(list(named_dict.items()), columns = ['Name', 'Temperature'])

temperature

Name  Temperature
0  Maxine           30
1   James           45
2  Amanda          -10

In [57]:
#b) Recreate the DataFrame temperatures in Part (a) with custom indices using
#the index keyword argument and a list containing 'Morning', 'Afternoon' and 'Evening'.
temperature = pd.DataFrame(list(named_dict.items()), columns = ['Name', 'Temperature'], index = ['Morning', 'Afternoon' ,'Evening'])

temperature

Name  Temperature
Morning    Maxine           30
Afternoon   James           45
Evening    Amanda          -10

In [59]:
# c) Select from temperatures the column of temperature readings for 'Maxine'.

temperature.loc['Morning']

Name           Maxine
Temperature        30
Name: Morning, dtype: object

In [60]:
# d) Select from temperatures the row of 'Morning' temperature readings.
temperature.iloc[0]

Name           Maxine
Temperature        30
Name: Morning, dtype: object

In [55]:
# e) Select from temperatures the rows for 'Morning' and 'Evening' temperature readings.
temperature.loc[['Morning', 'Evening']]

Name  Temperature
Morning  Maxine           30
Evening  Amanda          -10

In [54]:
# e) Select from temperatures the rows for 'Morning' and 'Evening' temperature readings.
temperature.iloc[[0, 2]]#thuis gives two rows that not consecutive

Name  Temperature
Morning  Maxine           30
Evening  Amanda          -10

In [62]:
temperature.describe()

Temperature
count     3.000000
mean     21.666667
std      28.431204
min     -10.000000
25%      10.000000
50%      30.000000
75%      37.500000
max      45.000000